[package]
name = "mariana"
version = "0.1.0"
edition = "2024"

[dependencies]
puerto={path = "../../dinvk-puerto/puerto"}
bitfield = "0.19.0"
obfstr = "0.4.4"
# 关闭memchr库默认的功能特性,强制让其工作在#![no_std]环境下.详见rust相关/crates
memchr = { version = "2.7.4", default-features = false }

[features]
desync = []

[build-dependencies]
cc="1.2.19"